# Файл docker-compose должен начинаться с тега версии.
version: "3.7"

# Следует учитывать, что docker-composes работает с сервисами.
# 1 сервис = 1 контейнер.
# Сервисом может быть клиент, сервер, сервер баз данных
# Раздел, в котором будут описаны сервисы, начинается с 'services'.
services:

  # Первый сервис (контейнер): веб-сервер.
  # Назвать его можно так, как нужно разработчику.
  # Понятное название сервиса помогает определить его роль.
  # Здесь мы, для именования соответствующего сервиса, используем ключевое слово 'web'.
  web:
    # команда image означает,что скачиваем готовый образ контейнера с DockerHub
    image: nginx:latest
    # Если мы хотим обратиться к серверу с нашего компьютера (находясь за пределами контейнера),
    # мы должны организовать перенаправление этого порта на порт компьютера.
    # Сделать это нам поможет ключевое слово 'ports'.
    # При его использовании применяется следующая конструкция: [порт компьютера]:[порт контейнера]
    # В нашем случае нужно использовать порт компьютера 80 и организовать его связь с портом
    # 80 контейнера (так как именно на этот порт сервер
    # ожидает поступления запросов)
    ports:
      - 127.0.0.1:80:80
    # параметр volumes используется для монтирования локальной дерриктории с дерикторией контейнера
    # При его использовании применяется следующая конструкция: [локальная директория]:[директория контейнера]
    volumes:
      - ./app:/var/www/html
      - ./configs/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx

    # Ключевое слово 'depends_on' позволяет указывать, должен ли сервис,
    # прежде чем запуститься, ждать, когда будут готовы к работе другие сервисы.
    # Нам нужно, чтобы сервис 'web' дождался бы готовности к работе сервиса 'php'
    depends_on:
      - php

  php:
    # Ключевое слово 'build' означает,что мы не  бубдем  использовать готовый  образ для контейнера,
    # а воспользуемся собственной сборкой из нашего Dockerfile
    # Здесь 'php' соответствует локальной директории, которая содержит
    # файл Dockerfile для создания контейнера php-fpm
    build:
      context: php
    #с помощью ключевого слова environment мы можем задать переменные окружения
    environment:
      PHP_IDE_CONFIG: "serverName=PhpServerBase"
    volumes:
      - ./app:/var/www/html
      - ./php_ini/php.ini:/usr/local/etc/php/php.ini
    links:
      - memcached

  mysql:
    image: mysql:8.0
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: simple_site2
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test
    volumes:
      - ./databases/mysql:/var/lib/mysql

  memcached:
    container_name: simple_site2_memcached
    image: memcached:latest

  phpmyadmin:
    container_name: simple_site2_phpmyadmin
    image: phpmyadmin:latest
    links:
      - mysql
    ports:
    - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  redis:
    image: redis:latest
    ports:
      - 6379:6379